/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tasnim' at '5/14/17 2:06 PM' with Gradle 2.14.1
 *
 * @author tasnim, @date 5/14/17 2:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
